import { expect, test } from "@playwright/test";
import { PDFDocument } from "pdf-lib";

test("standalone skylight calculator creates a branded PDF without opening system access", async ({ page, context }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("console", (message) => {
    if (message.type() === "error") errors.push(message.text());
  });
  const response = await page.goto("/skylight");
  expect(response?.status()).toBe(200);
  expect(response?.headers()["x-robots-tag"]).toContain("noindex");
  await expect(page.getByRole("heading", { name: "Skylight cost calculator" })).toBeVisible();
  await expect(page.locator('meta[name="robots"]')).toHaveAttribute("content", /noindex/);
  await expect(page.locator("main a")).toHaveCount(0);
  await expect(page.locator("main nav")).toHaveCount(0);
  await expect(page.locator('nextjs-portal [role="dialog"]')).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Generate quotation" })).toBeDisabled();

  await page.getByLabel("Connector", { exact: false }).fill("2.5");
  await page.locator("#quantity-glass").fill("10");
  await page.locator("#quantity-brackets").fill("4");
  await page.locator("#quantity-screws").fill("2");
  await expect(page.getByTestId("line-connector").locator("output")).toHaveCount(0);
  await expect(page.getByText("Item total", { exact: true })).toHaveCount(0);
  await expect(page.getByText("$86.25", { exact: true })).toHaveCount(0);
  await expect(page.getByTestId("standard-total")).toHaveText("$1,446.25");
  await expect(page.getByTestId("laminated-total")).toHaveText("$1,996.25");
  const other = page.locator("#other-amount");
  await expect(other).toHaveValue("");
  await other.fill("125.75");
  await expect(page.getByTestId("standard-total")).toHaveText("$1,572.00");
  await expect(page.getByTestId("laminated-total")).toHaveText("$2,122.00");
  await other.fill("-1");
  await expect(other).toHaveAttribute("aria-invalid", "true");
  await expect(page.getByTestId("standard-total")).toHaveText("—");
  await other.fill("");
  await expect(page.getByTestId("standard-total")).toHaveText("$1,446.25");
  const steel = page.getByLabel("Steel reinforcement", { exact: false });
  await expect(steel).toHaveValue("");
  await steel.fill("200.25");
  await expect(page.getByTestId("standard-total")).toHaveText("$1,646.50");
  await expect(page.getByTestId("laminated-total")).toHaveText("$2,196.50");
  await steel.fill("-1");
  await expect(steel).toHaveAttribute("aria-invalid", "true");
  await steel.fill("");
  await page.locator("#quantity-screws").fill("1.5");
  await expect(page.locator("#quantity-screws")).toHaveAttribute("aria-invalid", "true");
  await expect(page.getByRole("button", { name: "Generate quotation" })).toBeDisabled();
  await page.locator("#quantity-screws").fill("2");
  await expect(page.getByRole("button", { name: "Generate quotation" })).toBeDisabled();
  await page.getByLabel("Customer name").fill("Skylight Test Customer");
  await page.getByLabel("Salesperson name").fill("Ahmed Hassan");
  await expect(page.getByText("Unit price", { exact: true })).toHaveCount(0);
  await expect(page.getByText("$34.50", { exact: false })).toHaveCount(0);
  await page.getByLabel("Project name").fill("Baghdad Skylight");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole("button", { name: "Generate quotation" }).click();
  const quotation = page.locator("#skylight-quotation");
  await expect(quotation.getByText("$1,996.25", { exact: true })).toBeVisible();
  await expect(quotation.getByTestId("quotation-standard-total")).toHaveText("$1,446.25");
  await expect(quotation.getByTestId("quotation-laminated-total")).toHaveText("$1,996.25");
  await expect(quotation.getByText("Glass", { exact: true })).toBeVisible();
  await expect(quotation.getByText("Skylight Test Customer")).toBeVisible();
  await expect(quotation.getByText("Ahmed Hassan")).toBeVisible();
  await expect(quotation.getByRole("columnheader", { name: "Unit price" })).toHaveCount(0);
  await expect(quotation.getByRole("columnheader", { name: "Total", exact: true })).toHaveCount(0);
  await expect(quotation.getByText("$86.25", { exact: true })).toHaveCount(0);
  await expect(quotation.getByText(/\$175.00\/m²|\$55.00\/m²/)).toHaveCount(0);
  expect(await quotation.locator("img").evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download quotation PDF" }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toMatch(/^SK-.*\.pdf$/);
  expect(await download.failure()).toBeNull();
  const stream = await download.createReadStream();
  const chunks: Buffer[] = [];
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk));
  const pdf = Buffer.concat(chunks);
  expect(pdf.subarray(0, 5).toString()).toBe("%PDF-");
  expect(pdf.length).toBeGreaterThan(10000);
  await page.getByRole("button", { name: "Edit calculation" }).click();
  await expect(page.locator("#quantity-glass")).toHaveValue("10");
  await page.getByRole("button", { name: "Generate quotation" }).click();
  await expect(quotation.getByText("$1,446.25", { exact: true })).toBeVisible();
  await expect(quotation.getByTestId("quotation-laminated-total")).toHaveText("$1,996.25");
  expect(errors).toEqual([]);

  const protectedPage = await context.newPage();
  await protectedPage.goto("/dashboard");
  await expect(protectedPage).toHaveURL(/\/login\?/);
});

test("all materials and manual amounts fit one A4 quotation", async ({ page }) => {
  await page.goto("/skylight");
  for (const input of await page.locator('input[id^="quantity-"]').all()) {
    await input.fill("10");
  }
  await expect(page.getByTestId("standard-total")).toHaveText("$3,219.00");
  await expect(page.getByTestId("laminated-total")).toHaveText("$3,769.00");
  await page.getByLabel("Other", { exact: false }).fill("125.75");
  await expect(page.getByTestId("standard-total")).toHaveText("$3,344.75");
  await expect(page.getByTestId("laminated-total")).toHaveText("$3,894.75");
  await page.getByLabel("Steel reinforcement", { exact: false }).fill("200.25");
  await expect(page.getByTestId("standard-total")).toHaveText("$3,545.00");
  await expect(page.getByTestId("laminated-total")).toHaveText("$4,095.00");
  await page.getByLabel("Customer name").fill("Customer ".repeat(11));
  await page.getByLabel("Salesperson name").fill("Salesperson ".repeat(9));
  await page.getByLabel("Project name").fill("Skylight project ".repeat(6));
  await page.getByLabel("Notes").fill("Quotation notes for skylight materials. ".repeat(9));
  await page.getByLabel("Exchange rate (IQD per 1 USD)").fill("1540");
  await page.getByRole("switch", { name: "Convert totals to IQD" }).click();
  await page.getByRole("button", { name: "Generate quotation" }).click();
  await expect(page.locator("#skylight-quotation tbody tr")).toHaveCount(14);
  await expect(page.locator("#skylight-quotation").getByText("Other", { exact: true })).toBeVisible();
  await expect(page.locator("#skylight-quotation").getByText("Steel reinforcement", { exact: true })).toBeVisible();
  await expect(page.locator("#skylight-quotation").getByText("IQD 6,306,300", { exact: true })).toBeVisible();
  await expect(page.locator("#skylight-quotation").getByText("$125.75", { exact: true })).toHaveCount(0);
  // Match the fixed A4 dimensions applied by the existing PDF exporter.
  const dimensions = await page.locator(".pdf-page").evaluate((element) => {
    const page = element as HTMLElement;
    Object.assign(page.style, { width: "210mm", height: "297mm", minHeight: "297mm", maxWidth: "none" });
    return { height: page.clientHeight, content: page.scrollHeight };
  });
  expect(dimensions.content).toBeLessThanOrEqual(dimensions.height);
});

test("manual currency conversion updates both totals and the quotation without changing USD inputs", async ({ page }) => {
  await page.goto("/skylight");
  await page.locator("#quantity-glass").fill("10");
  await page.locator("#other-amount").fill("125.75");
  await page.locator("#steel-amount").fill("200.25");
  await page.getByLabel("Salesperson name").fill("Currency test salesperson");
  const toggle = page.getByRole("switch", { name: "Convert totals to IQD" });
  const rate = page.getByLabel("Exchange rate (IQD per 1 USD)");
  await expect(rate).toHaveValue("");
  await expect(toggle).toBeDisabled();
  await rate.fill("0");
  await expect(toggle).toBeDisabled();
  await rate.fill("1540");
  await expect(page.getByTestId("standard-total")).toHaveText("$1,526.00");
  await toggle.click();
  await expect(page.getByTestId("standard-total")).toHaveText("IQD 2,350,040");
  await expect(page.getByTestId("laminated-total")).toHaveText("IQD 3,197,040");
  await rate.fill("1560");
  await expect(page.getByTestId("standard-total")).toHaveText("IQD 2,380,560");
  await expect(page.getByTestId("laminated-total")).toHaveText("IQD 3,238,560");
  await rate.fill("");
  await expect(page.getByTestId("standard-total")).toHaveText("—");
  await expect(page.getByRole("button", { name: "Generate quotation" })).toBeDisabled();
  await toggle.click();
  await expect(page.getByTestId("standard-total")).toHaveText("$1,526.00");
  await rate.fill("1560");
  await toggle.click();
  await page.getByRole("button", { name: "Generate quotation" }).click();
  const quotation = page.locator("#skylight-quotation");
  await expect(quotation.getByText("Currency: IQD")).toBeVisible();
  await expect(quotation.getByTestId("quotation-standard-total")).toHaveText("IQD 2,380,560");
  await expect(quotation.getByTestId("quotation-laminated-total")).toHaveText("IQD 3,238,560");
  await expect(quotation.getByText(/1 USD = 1,560 IQD/)).toBeVisible();
  const pending = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download quotation PDF" }).click();
  expect(await (await pending).failure()).toBeNull();
  await page.getByRole("button", { name: "Edit calculation" }).click();
  await expect(rate).toHaveValue("1560");
  await expect(toggle).toHaveAttribute("aria-checked", "true");
  await expect(page.locator("#other-amount")).toHaveValue("125.75");
  await expect(page.locator("#steel-amount")).toHaveValue("200.25");
  await toggle.click();
  await expect(page.getByTestId("standard-total")).toHaveText("$1,526.00");
});

test("PDF and JPG attachments are appended in order and can be removed", async ({ page }) => {
  await page.goto("/skylight");
  await page.locator("#quantity-glass").fill("10");
  await page.getByLabel("Customer name").fill("Attachment customer");
  await page.getByLabel("Salesperson name").fill("Sara Ahmed");
  const source = await PDFDocument.create();
  source.addPage([420, 595]).drawText("Drawing page one");
  source.addPage([595, 420]).drawText("Drawing page two");
  const sourceBytes = Buffer.from(await source.save());
  const jpeg = await page.evaluate(() => {
    const canvas = document.createElement("canvas");
    canvas.width = 640;
    canvas.height = 400;
    const context = canvas.getContext("2d")!;
    context.fillStyle = "#0057a8";
    context.fillRect(0, 0, 640, 400);
    return canvas.toDataURL("image/jpeg").split(",")[1];
  });
  const picker = page.getByLabel("Attachments", { exact: false });
  await picker.setInputFiles({ name: "invalid.txt", mimeType: "text/plain", buffer: Buffer.from("invalid") });
  await expect(page.locator("main").getByRole("alert")).toContainText("valid PDF or JPG");
  await picker.setInputFiles([
    { name: "drawing.pdf", mimeType: "application/pdf", buffer: sourceBytes },
    { name: "site.jpg", mimeType: "image/jpeg", buffer: Buffer.from(jpeg, "base64") },
  ]);
  await expect(page.getByRole("list", { name: "Quotation attachments" }).getByRole("listitem")).toHaveCount(2);
  await expect(page.locator("main").getByRole("alert")).toHaveCount(0);
  await page.getByRole("button", { name: "Generate quotation" }).click();
  await expect(page.getByRole("region", { name: "Included attachments" })).toContainText("drawing.pdf · 2 pages");
  await expect(page.locator("#skylight-quotation footer")).toContainText("1 / 4");
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download quotation PDF" }).click();
  const download = await downloadPromise;
  expect(await download.failure()).toBeNull();
  const stream = await download.createReadStream();
  const chunks: Buffer[] = [];
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk));
  const result = await PDFDocument.load(Buffer.concat(chunks));
  expect(result.getPageCount()).toBe(4);
  expect(result.getPage(1).getSize()).toEqual({ width: 420, height: 595 });
  expect(result.getPage(2).getSize()).toEqual({ width: 595, height: 420 });
  expect(result.getPage(3).getWidth()).toBeGreaterThan(result.getPage(3).getHeight());
  expect(result.getPage(3).node.Resources()?.toString()).toContain("Image-");
  await page.getByRole("button", { name: "Edit calculation" }).click();
  await expect(page.getByLabel("Salesperson name")).toHaveValue("Sara Ahmed");
  await page.getByRole("button", { name: "Remove drawing.pdf" }).click();
  await expect(page.getByRole("list", { name: "Quotation attachments" }).getByRole("listitem")).toHaveCount(1);
  await page.getByRole("button", { name: "Generate quotation" }).click();
  await expect(page.getByRole("region", { name: "Included attachments" })).not.toContainText("drawing.pdf");
  await expect(page.locator("#skylight-quotation footer")).toContainText("1 / 2");
});
