"use client";
import { LanguageSwitcher } from '@/components/i18n/LanguageSwitcher';
import { useI18n } from '@/components/i18n/I18nProvider';
import { useEffect,useState } from 'react';
import { OutdoorIntake } from '@/components/intake/OutdoorIntake';
import { InitialMeasurements } from '@/components/measurements/InitialMeasurements';
import { FollowUpWorkspace } from '@/components/workflow/FollowUpWorkspace';
import { SalesReminders } from '@/components/workflow/SalesReminders';
import { SalesDashboard } from '@/components/workflow/SalesDashboard';
import { ProjectWorkspace } from '@/components/workflow/ProjectWorkspace';
import { SyncConflicts } from "./SyncConflicts";
import { OfflineStatus } from './OfflineStatus';
import { readFieldState } from '@/lib/offline/store';
import type { FieldState } from '@/lib/offline/types';
export function OfflineWorkspace(){
 const { term } = useI18n();
 const [state,setState]=useState<FieldState|null>(null);const [loaded,setLoaded]=useState(false);const [path,setPath]=useState('/intake');const [message,setMessage]=useState('');
 useEffect(()=>{let live=true;async function refresh(){const saved=await readFieldState().catch(()=>null);if(live){setState(saved);setLoaded(true);}}const params=new URLSearchParams(location.search);const timer=setTimeout(()=>{setPath((params.get('path')??(params.get('project')?'/initial-measurements/'+params.get('project'):'/intake')).split('#')[0]);void refresh();},0);window.addEventListener('field-change',refresh);return()=>{live=false;clearTimeout(timer);window.removeEventListener('field-change',refresh);};},[]);
 function navigate(next:string){next=next.split('#')[0];if(/^\/projects\/[0-9a-f-]{36}\/follow-ups$/i.test(next)||/^\/(dashboard|intake|projects|mini-crm)$/.test(next)||/^\/initial-measurements\/[0-9a-f-]{36}$/i.test(next)){setPath(next);setMessage('');history.replaceState(null,'','/offline?path='+encodeURIComponent(next));}else if(navigator.onLine && !state?.queue.length)location.assign(next);else setMessage('Quotations and contracts need an internet connection. Your field work stays saved here.');}
 const projectId=path.startsWith('/initial-measurements/')?path.split('/')[2]:null;
 return <div className="min-h-dvh bg-slate-50 text-slate-900"><header className="border-b border-slate-200 bg-white px-5 py-5"><div className="mx-auto flex max-w-5xl flex-wrap items-center justify-between gap-4"><span className="text-xl font-semibold">{term("Alumex · Device workspace")}</span><a href="/intake" className="text-sm text-blue-600">{term("Open online system")}</a><LanguageSwitcher/></div></header><OfflineStatus/><SalesReminders/>{loaded&&!state?<div className="mx-auto max-w-xl p-8"><h1 className="text-xl font-semibold">{term("Sign in online to prepare this device")}</h1><p className="mt-3 text-sm text-slate-600">{term("Offline work is available after an employee signs in and the device downloads its workspace.")}</p><a href="/login" className="mt-5 inline-block text-blue-600">{term("Sign in")}</a></div>:state?<><nav className="mx-auto flex max-w-5xl flex-wrap gap-2 px-5 pt-5">{[['/dashboard','Dashboard'],['/intake','New project'],['/projects','Projects'],['/mini-crm','Follow-ups']].map(([href,label])=><button key={href} onClick={()=>navigate(href)} className={`min-h-11 rounded-md px-4 text-sm font-semibold ${path===href?'bg-blue-600 text-white':'border border-slate-300 bg-white text-slate-700'}`}>{term(label)}</button>)}<span className="w-full py-2 text-xs text-slate-500">{term('Signed in as {name}. Saved changes sync when the app is open and connected. Don’t clear site data while changes are waiting to sync.',{name:state.actor.name==='Employee'?term('Employee'):state.actor.name})}</span></nav><SyncConflicts state={state}/>{message&&<p role="alert" className="mx-auto max-w-5xl px-5 pt-4 text-amber-800">{term(message)}</p>}<div onClickCapture={event=>{const link=(event.target as HTMLElement).closest('a[href]');const href=link?.getAttribute('href');if(href?.startsWith('/')&&!href.startsWith('/api/')){event.preventDefault();event.stopPropagation();navigate(href);}}}>{path==='/dashboard'?<SalesDashboard/>:/^\/projects\/[^/]+\/follow-ups$/.test(path)?<FollowUpWorkspace key={path} projectId={path.split('/')[2]}/>:projectId?<InitialMeasurements key={projectId} projectId={projectId}/>:path==='/projects'||path==='/mini-crm'?<ProjectWorkspace key={path} followUps={path==='/mini-crm'}/>:<OutdoorIntake key={path}/>}</div></>:<p className="p-8">{term("Loading saved workspace…")}</p>}</div>;
}
