"use client";
import { useI18n } from '@/components/i18n/I18nProvider';
import { needsSalesFollowUp } from '@/lib/workflow/stages';
import {useState} from 'react';
import type {FieldState} from '@/lib/offline/types';
import {reviewServerProject,retryReviewedProject,keepReviewedServerVersion} from '@/lib/offline/client';
export function SyncConflicts({state}:{state:FieldState}){
 const { term,errorMessage,formatDateTime } = useI18n();
 const [review,setReview]=useState<Awaited<ReturnType<typeof reviewServerProject>>|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 const changes=state.queue.filter(c=>c.error);if(!changes.length)return null;
 return <section className="mx-auto mt-5 max-w-5xl space-y-3 px-5"><h2 className="font-semibold text-amber-900">{term("Saved work needs attention")}</h2>{changes.map(c=><div key={c.id} className="rounded-md border border-amber-200 bg-white p-4 text-sm"><p className="font-semibold">{state.projects.find(p=>p.id===c.projectId)?.project_name} · {term(c.action)}</p><p className="mt-2 text-red-700">{errorMessage(c.error??'')}</p>{c.action==='follow-up'&&<p className="mt-2 whitespace-pre-wrap">{term("Your saved note:")} {String(c.payload.note??'')}<br/>{term("Follow-up:")} {c.payload.nextFollowUp?formatDateTime(String(c.payload.nextFollowUp)):term('None')}</p>}<button disabled={busy} className="mt-3 min-h-11 font-semibold text-blue-600" onClick={async()=>{setBusy(true);setMessage('');try{setReview(await reviewServerProject(c.projectId));}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>{term("Review server version")}</button>{review?.project.id===c.projectId&&<div className="mt-3 border-t border-slate-200 pt-3"><p>{term("Current server note:")} {review.project.project_notes||term("No note")}</p><p>{term("Current follow-up:")} {review.project.next_follow_up_at?formatDateTime(review.project.next_follow_up_at):term('None')}</p><p>{term("Site:")} {term(review.project.structure_readiness)}</p>{c.action==='follow-up'&&needsSalesFollowUp(review.project)&&<button disabled={busy} className="mt-3 min-h-11 rounded-md bg-blue-600 px-4 text-white" onClick={async()=>{setBusy(true);try{await retryReviewedProject(c.projectId,review.project.updated_at);setReview(null);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>{term("Use my saved note and retry")}</button>}<div className="mt-3 flex flex-wrap gap-3"><button className="min-h-11 text-blue-600 underline" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state.queue.filter(q=>q.projectId===c.projectId),null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`saved-field-work-${c.projectId}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>{term("Download my saved work")}</button><button disabled={busy} className="min-h-11 text-red-700 underline" onClick={async()=>{if(!confirm(term('Remove this device’s pending changes for this project and keep the server version? Download your saved work first if you need a copy.')))return;setBusy(true);try{await keepReviewedServerVersion(review);setReview(null);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>{term("Keep server version")}</button></div></div>}</div>)}{message&&<p role="alert" className="text-red-700">{errorMessage(message)}</p>}</section>;
}
