"use client";
import { useState } from 'react';
import type { CatalogItem } from '@/lib/workflow/pricing';
import { api,button,card,field,Notice,useResource,Workspace } from './ui';
export function CatalogWorkspace(){
 const {data,error,setError,loading,reload}=useResource<{items:CatalogItem[]}>('/api/catalog');const [busy,setBusy]=useState('');const [notice,setNotice]=useState('');
 async function save(event:React.FormEvent<HTMLFormElement>,id:string){event.preventDefault();setBusy(id);setError('');setNotice('');const price=Number(new FormData(event.currentTarget).get('price'));try{await api('/api/catalog',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,price})});await reload();setNotice('Catalog price saved. Existing quotations and contracts retain their agreed prices.');}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 return <Workspace title="Price catalog" description="Preset prices in IQD. New quotations use these rates; saved quotations and signed contracts keep their original prices."><Notice error={error}/>{notice&&<p role="status" className="mb-5 text-green-700">{notice}</p>}{loading?<p>Loading catalog…</p>:<div className="space-y-3">{data?.items.map(item=><form key={item.id} onSubmit={e=>void save(e,item.id)} className={`${card} grid items-end gap-4 sm:grid-cols-[1fr_180px_auto]`}><div><h2 className="font-semibold">{item.name}</h2><p className="mt-1 text-sm text-slate-500">{item.category?.replaceAll('_',' ')} · per {item.unit}{!item.is_active?' · Inactive':''}</p>{Number(item.unit_price)<=0&&<p className="mt-2 text-sm text-amber-700">Price required before quoting</p>}</div><label className="text-sm">Price (IQD)<input name="price" aria-label={`${item.name} price`} type="number" required min="1" step="1" defaultValue={item.unit_price} className={field}/></label><button disabled={!!busy} className={button}>{busy===item.id?'Saving…':'Save price'}</button></form>)}</div>}</Workspace>;
}
