"use client";
import { useState } from 'react';
import { useCurrentRole } from '@/components/auth/useCurrentRole';
import { api,button,card,field,Notice,useResource,Workspace } from './ui';
type Employee={id:string;full_name:string;username:string;role:string;status:string};
export function EmployeeWorkspace(){
 const {data,error,setError,loading,reload}=useResource<{users:Employee[]}>('/api/admin/users');const {role}=useCurrentRole();
 const [saving,setSaving]=useState(false);const [show,setShow]=useState(false);const [notice,setNotice]=useState('');
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(saving)return;const form=event.currentTarget;const values=new FormData(form);setSaving(true);setError('');setNotice('');try{await api('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(values))});form.reset();setNotice('Employee added. They can sign in with the username and password you set.');await reload();}catch(e){setError(e instanceof Error?e.message:'Unable to add employee.');}finally{setSaving(false);}}
 return <Workspace title="Employees" description="Add an employee and set their access role and sign-in credentials."><Notice error={error}/>{notice&&<p role="status" className="mb-5 rounded-md bg-green-50 p-4 text-sm text-green-800">{notice}</p>}<form onSubmit={submit} className={card}><div className="grid gap-5 sm:grid-cols-2"><label>Employee name<input required name="fullName" maxLength={150} autoComplete="off" className={field}/></label><label>Role<select required name="role" aria-label="Role" className={field}><option value="">Choose role</option>{['Indoor Sales','Outdoor Sales','Operations Manager','Project Manager','HR',...(role==='Admin'?['Admin']:[])].map(r=><option key={r}>{r}</option>)}</select></label><label>Username<input required name="username" autoComplete="off" pattern="[a-zA-Z0-9_.-]{3,64}" className={field}/></label><label>Password<input required name="password" aria-label="Password" aria-describedby="password-help" type={show?'text':'password'} autoComplete="new-password" minLength={8} className={field}/><span id="password-help" className="mt-2 block text-xs text-slate-500">At least 8 characters. Passwords are never shown in the employee list.</span></label></div><label className="my-5 flex items-center gap-2 text-sm"><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/>Show password while entering</label><button disabled={saving} className={button}>{saving?'Adding employee…':'Add employee'}</button></form><h2 className="mt-9 mb-4 text-lg font-semibold">Team</h2>{loading?<p>Loading employees…</p>:<div className="space-y-3">{data?.users.map(e=><div key={e.id} className={`${card} flex flex-wrap items-center justify-between gap-3`}><div><p className="font-semibold">{e.full_name||e.username}</p><p className="mt-1 text-sm text-slate-500">{e.username}</p></div><span className="text-sm text-slate-600">{e.role} · {e.status}</span></div>)}</div>}</Workspace>;
}
