"use client";
import { useState } from 'react';
import { api,button,card,Notice,useResource,Workspace } from './ui';
type Project={id:string;project_name:string;project_number:string;address:string;client:{name:string;mobile:string};handoff:{stage:string;revision:number;signed_at:string;specifications?:{openingId:string;system:string;glass:string;extras:{name:string;quantity:number;unit:string}[]}[]};openings:{id:string;floor:string;room:string;width:number;height:number;opening_type:string;opening_direction:string|null}[]};
export function OperationsWorkspace(){
 const {data,error,setError,loading,reload}=useResource<{projects:Project[];canAccept:boolean}>('/api/operations');const [busy,setBusy]=useState('');
 async function accept(p:Project){setBusy(p.id);setError('');try{await api('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId:p.id,revision:p.handoff.revision})});await reload();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 return <Workspace title="Operations" description="Projects appear here after the signed client contract is saved."><Notice error={error}/>{loading?<p>Loading operations…</p>:!data?.projects.length?<div className={card}>No signed projects awaiting operations.</div>:<div className="space-y-5">{data.projects.map(p=><article key={p.id} className={card}><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-semibold text-blue-600">{p.project_number}</p><h2 className="mt-2 text-xl font-semibold">{p.project_name}</h2></div><span className="text-sm text-green-700">{p.handoff.stage==='operations'?'Work started':'Ready to start'}</span></div><p className="mt-4 text-sm">{p.client?.name} · {p.client?.mobile}</p><p className="mt-2 text-sm text-slate-600">{p.address}</p><details className="mt-5"><summary className="cursor-pointer py-2 font-semibold">{p.openings.length} openings</summary><div className="mt-3 grid gap-3 sm:grid-cols-2">{p.openings.map((o,i)=><div key={o.id} className="rounded-md bg-slate-50 p-4 text-sm"><p className="font-semibold">Opening {i+1} · {o.opening_type} {o.opening_direction}</p><p className="mt-2">Floor {o.floor} · {o.room}</p><p className="mt-1">{o.width} × {o.height} cm</p>{p.handoff.specifications?.filter(s=>s.openingId===o.id).map(s=><div key={s.openingId} className="mt-3 text-slate-600"><p>{s.system} · {s.glass}</p>{s.extras.map((e,i)=><p key={i}>{e.name} · {e.quantity} {e.unit}</p>)}</div>)}</div>)}</div></details>{data.canAccept&&p.handoff.stage==='signed'&&<button disabled={!!busy} onClick={()=>void accept(p)} className={`${button} mt-5`}>{busy===p.id?'Starting…':'Start project work'}</button>}</article>)}</div>}</Workspace>;
}
