"use client";
import { useI18n } from '@/components/i18n/I18nProvider';
import { useState } from 'react';
import { api,button,card,Notice,useResource,Workspace } from './ui';
type Project={id:string;project_name:string;project_number:string;address:string;client:{name:string;mobile:string};handoff:{stage:string;revision:number;signed_at:string;additionalItems?:{name:string;quantity:number;unit:string}[];specifications?:{openingId:string;system:string;glass:string;extras:{name:string;quantity:number;unit:string}[]}[]};openings:{id:string;floor:string;room:string;width:number;height:number;opening_type:string;opening_direction:string|null}[]};
export function OperationsWorkspace(){
 const { term,formatNumber } = useI18n();
 const {data,error,setError,loading,reload}=useResource<{projects:Project[];canAccept:boolean}>('/api/operations');const [busy,setBusy]=useState('');
 async function accept(p:Project){setBusy(p.id);setError('');try{await api('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId:p.id,revision:p.handoff.revision})});await reload();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 return <Workspace title={term("Operations")} description={term("Projects appear here after the signed client contract is saved.")}><Notice error={error}/>{loading?<p>{term("Loading operations…")}</p>:!data?.projects.length?<div className={card}>{term("No signed projects awaiting operations.")}</div>:<div className="space-y-5">{data.projects.map(p=><article key={p.id} className={card}><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-semibold text-blue-600">{p.project_number}</p><h2 className="mt-2 text-xl font-semibold">{p.project_name}</h2></div><span className="text-sm text-green-700">{p.handoff.stage==='operations'?term("Work started"):term("Ready to start")}</span></div><p className="mt-4 text-sm">{p.client?.name} · <bdi dir="ltr">{p.client?.mobile}</bdi></p><p className="mt-2 text-sm text-slate-600">{p.address}</p><details className="mt-5"><summary className="cursor-pointer py-2 font-semibold">{term('{count} openings',{count:formatNumber(p.openings.length)})}</summary><div className="mt-3 grid gap-3 sm:grid-cols-2">{p.openings.map((o,i)=><div key={o.id} className="rounded-md bg-slate-50 p-4 text-sm"><p className="font-semibold">{term('Opening {number}',{number:formatNumber(i+1)})} · {term(o.opening_type)} {o.opening_direction?term(o.opening_direction):''}</p><p className="mt-2">{term("Floor")} {term(o.floor)} · {term(o.room)}</p><p className="mt-1">{formatNumber(o.width)} × {formatNumber(o.height)} {term("cm")}</p>{p.handoff.specifications?.filter(s=>s.openingId===o.id).map(s=><div key={s.openingId} className="mt-3 text-slate-600"><p>{term(s.system)} · {term(s.glass)}</p>{s.extras.map((e,i)=><p key={i}>{term(e.name)} · {formatNumber(e.quantity)} {term(e.unit)}</p>)}</div>)}</div>)}</div></details>{!!p.handoff.additionalItems?.length&&<section className="mt-5 rounded-md bg-slate-50 p-4"><h3 className="font-semibold">{term("Additional products & services")}</h3><ul className="mt-3 space-y-2 text-sm">{p.handoff.additionalItems.map((item,i)=><li key={i}>{term(item.name)} · {formatNumber(item.quantity)} {term(item.unit)}</li>)}</ul></section>}{data.canAccept&&p.handoff.stage==='signed'&&<button disabled={!!busy} onClick={()=>void accept(p)} className={`${button} mt-5`}>{busy===p.id?term("Starting…"):term("Start project work")}</button>}</article>)}</div>}</Workspace>;
}
