"use client";
import Link from 'next/link';
import { useState } from 'react';
import { api,button,card,field,Notice,secondary,useResource,Workspace } from './ui';
type Project={id:string;project_name:string;project_number:string;address:string;phone:string|null;structure_readiness:string;sales_status:string;next_follow_up_at:string|null;registeredBy:string;created_at:string;project_notes:string|null;pending?:boolean};
function nextRoute(p:Project){return p.structure_readiness!=='ready'?'/mini-crm':['new_lead','ready_for_quotation'].includes(p.sales_status)?`/${p.sales_status==='new_lead'?'initial-measurements':'quotation'}/${p.id}`:['contract_generated','contract_signed','transferred_to_operations'].includes(p.sales_status)?`/contract/${p.id}`:`/quotation/${p.id}`;}
export function ProjectWorkspace({followUps=false}:{followUps?:boolean}){
 const {data,error,setError,loading,reload}=useResource<{projects:Project[]}>('/api/workspace');const [busy,setBusy]=useState('');const [notice,setNotice]=useState('');
 async function update(p:Project,action:string,form?:HTMLFormElement){setBusy(p.id);setError('');setNotice('');const values=form?new FormData(form):null;const date=values?.get('nextFollowUp');try{await api('/api/workspace',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId:p.id,action,note:values?.get('note'),nextFollowUp:date?new Date(String(date)).toISOString():null})});await reload();setNotice(action==='ready'?'Site marked ready. Open the project from Projects to record measurements.':'Follow-up saved.');}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 const projects=(data?.projects??[]).filter(p=>!followUps||p.structure_readiness!=='ready');
 return <Workspace title={followUps?'Mini CRM':'Projects'} description={followUps?'Follow up on sites that are not ready. Move them to initial measurements when the site is ready.':'Every client project, its current step, and the employee who registered it.'}><Notice error={error}/>{notice&&<p role="status" className="mb-5 text-green-700">{notice}</p>}<Link href="/intake" className={`${button} mb-6 inline-block`}>New client & project</Link>{loading?<p>Loading projects…</p>:!projects.length?<div className={card}>{followUps?'No sites awaiting follow-up.':'No projects yet. Start by registering a client.'}</div>:<div className="space-y-4">{projects.map(p=><article key={p.id} className={card}><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-semibold text-blue-600">{p.project_number}{p.pending?" · Saved on device":""}</p><h2 className="mt-2 text-xl font-semibold">{p.project_name}</h2><p className="mt-2 text-sm text-slate-600">{p.address}</p></div><span className="h-fit rounded-full bg-slate-100 px-3 py-1 text-xs font-medium">{p.structure_readiness!=='ready'?'Awaiting site readiness':p.sales_status.replaceAll('_',' ')}</span></div>{p.phone&&<a href={`tel:${p.phone}`} className="mt-3 inline-block text-sm font-medium text-blue-600">{p.phone}</a>}<p className="mt-4 text-xs text-slate-500">Registered by {p.registeredBy} · {new Date(p.created_at).toLocaleString()}</p>{followUps?<form onSubmit={e=>{e.preventDefault();void update(p,'follow-up',e.currentTarget);}} className="mt-5 border-t border-slate-100 pt-5"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Next follow-up<input required name="nextFollowUp" type="datetime-local" defaultValue={p.next_follow_up_at?new Date(new Date(p.next_follow_up_at).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):''} className={field}/></label><label className="text-sm">Follow-up note<input name="note" maxLength={2000} defaultValue={p.project_notes??''} className={field}/></label></div><div className="mt-4 flex flex-wrap gap-3"><button disabled={!!busy} className={secondary}>Save follow-up</button><button type="button" disabled={!!busy} onClick={()=>void update(p,'ready')} className={button}>Site is ready → Measurements</button></div></form>:<Link href={nextRoute(p)} className="mt-5 inline-block py-2 text-sm font-semibold text-blue-600">Open project →</Link>}</article>)}</div>}</Workspace>;
}
