"use client";
import Link from 'next/link';
import { useState } from 'react';
import { defaultSystem,systemOptions,money,type CatalogItem,type MeasuredOpening,type OpeningChoice,type QuoteSnapshot } from '@/lib/workflow/pricing';
import type { SalesFlow } from '@/lib/workflow/types';
import { api,button,card,field,Notice,secondary,useResource,Workspace } from './ui';
type QuoteData={project:{project_name:string;project_number:string;address:string;sales_status:string};client:{name:string;mobile:string};openings:MeasuredOpening[];catalog:CatalogItem[];flow:SalesFlow|null};
export function QuoteLines({quote}:{quote:QuoteSnapshot}){return <div className="space-y-4">{quote.lines.map((line,index)=><div key={line.opening.id} className="break-inside-avoid border-b border-slate-200 pb-4"><div className="flex justify-between gap-3"><h3 className="font-semibold">Opening {index+1} · {line.opening.opening_type} {line.opening.opening_direction}</h3><p className="whitespace-nowrap font-semibold">{money(line.total)}</p></div><p className="mt-2 text-sm text-slate-600">Floor {line.opening.floor} · {line.opening.room} · {line.opening.width} × {line.opening.height} cm · {line.area.toFixed(2)} m²</p>{[line.system,...(line.glass?[line.glass]:[]),...line.extras].map(item=><p key={item.id} className="mt-1 text-sm text-slate-600">{item.name}: {item.quantity.toLocaleString(undefined,{maximumFractionDigits:4})} {item.unit} × {money(item.rate)} = {money(item.total)}</p>)}</div>)}<p className="text-end text-xl font-semibold">Total: {money(quote.total)}</p></div>;}
function QuoteEditor({data,projectId,reload}:{data:QuoteData;projectId:string;reload:()=>Promise<void>}){
 const {catalog,openings,flow}=data;
 const [choices,setChoices]=useState<OpeningChoice[]>(()=>openings.map(o=>{const saved=flow?.quotation.lines.find(l=>l.opening.id===o.id);return {openingId:o.id,systemId:saved?.system.id??defaultSystem(o,catalog)?.id??'',glassId:saved?.glass?.id??'',extras:saved?.extras.map(e=>({id:e.id,quantity:e.quantity}))??[]};}));
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [dirty,setDirty]=useState(!flow);const [approved,setApproved]=useState(false);
 const locked=!!flow&&!['quotation','approved'].includes(flow.stage);
 function edit(index:number,patch:Partial<OpeningChoice>){setChoices(c=>c.map((v,i)=>i===index?{...v,...patch}:v));setDirty(true);setApproved(false);}
 async function act(action:string){setBusy(true);setError('');try{await api(`/api/sales-flow/${projectId}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,choices,revision:flow?.revision??0,confirmed:approved})});await reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><Notice error={error}/>{!locked&&<div className="print:hidden"><p className="mb-5 rounded-md bg-blue-50 p-4 text-sm leading-6 text-blue-900">Alumex is selected by default. Rates come from the price catalog. Choose glass upgrades or add-ons only when requested by the client. Saving changes requires a new client approval.</p><div className="space-y-5">{openings.map((opening,index)=>{const choice=choices[index];return <section key={opening.id} className={card}><h2 className="font-semibold">Opening {index+1} · {opening.opening_type} {opening.opening_direction}</h2><p className="mt-2 text-sm text-slate-500">Floor {opening.floor} · {opening.room} · {opening.width} × {opening.height} cm</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm">System / product<select value={choice.systemId} onChange={e=>edit(index,{systemId:e.target.value})} className={field}><option value="">Choose system</option>{systemOptions(opening,catalog).map(p=><option key={p.id} value={p.id}>{p.name} · {p.unit_price>0?`${money(p.unit_price)} / ${p.unit}`:'Price required'}</option>)}</select></label><label className="text-sm">Glass<select value={choice.glassId} onChange={e=>edit(index,{glassId:e.target.value})} className={field}><option value="">Standard glass included</option>{catalog.filter(p=>/glass/i.test(p.name)).map(p=><option key={p.id} value={p.id}>{p.name} · {p.unit_price>0?`+${money(p.unit_price)} / ${p.unit}`:'Price required'}</option>)}</select></label></div><div className="mt-5"><label className="text-sm">Add an extra<select value="" onChange={e=>{if(e.target.value)edit(index,{extras:[...choice.extras,{id:e.target.value,quantity:1}]});}} className={field}><option value="">Choose add-on</option>{catalog.filter(p=>(p.category==='addon'||p.category==='service')&&p.id!==choice.systemId&&p.id!==choice.glassId&&!choice.extras.some(e=>e.id===p.id)).map(p=><option key={p.id} value={p.id}>{p.name} · {p.unit_price>0?`${money(p.unit_price)} / ${p.unit}`:'Price required'}</option>)}</select></label>{choice.extras.map(extra=>{const p=catalog.find(p=>p.id===extra.id);return <div key={extra.id} className="mt-3 flex flex-wrap items-center gap-3 rounded-md bg-slate-50 p-3"><span className="flex-1 text-sm">{p?.name}</span>{p?.unit!=='sqm'&&<label className="text-xs">{p?.unit==='meter'?'Length (m)':'Add-on quantity'}<input aria-label={`${p?.name} quantity`} type="number" min="0.01" step="0.01" value={extra.quantity} className={`${field} max-w-28`} onChange={e=>edit(index,{extras:choice.extras.map(x=>x.id===extra.id?{...x,quantity:Number(e.target.value)}:x)})}/></label>}<button type="button" className="min-h-11 px-3 text-sm text-red-700" onClick={()=>edit(index,{extras:choice.extras.filter(x=>x.id!==extra.id)})}>Remove</button></div>;})}</div></section>;})}</div><button disabled={busy||!dirty} onClick={()=>void act('save')} className={`${button} mt-5`}>{busy?'Saving…':flow?'Save revised quotation':'Generate quotation'}</button></div>}
 {flow&&<section className={`${card} mt-8`}><div className="mb-6 flex flex-wrap justify-between gap-4"><h2 className="text-xl font-semibold">Quotation · {data.project.project_number}</h2><span className="text-sm capitalize text-slate-500">{flow.stage}</span></div><p className="mb-5 text-sm">{data.client.name} · {data.client.mobile}<br/>{data.project.address}</p><QuoteLines quote={flow.quotation}/><div className="mt-6 flex flex-wrap gap-3 print:hidden"><button onClick={()=>window.print()} className={secondary}>Print quotation</button>{flow.stage==='quotation'&&<div className="w-full border-t border-slate-200 pt-5"><label className="mb-4 flex items-center gap-3 text-sm"><input type="checkbox" checked={approved} disabled={dirty} onChange={e=>setApproved(e.target.checked)}/>The client approved this saved quotation.</label><button disabled={busy||dirty||!approved} onClick={()=>void act('approve')} className={button}>Record client approval</button></div>}{flow.stage==='approved'&&<button disabled={busy||dirty} onClick={()=>void act('contract')} className={button}>Generate contract</button>}{locked&&<Link href={`/contract/${projectId}`} className={button}>Open contract →</Link>}</div></section>}
 </>;
}
export function QuotationWorkspace({projectId}:{projectId:string}){
 const resource=useResource<QuoteData>(`/api/sales-flow/${projectId}`);
 return <Workspace title="Quotation" description="Prepare the client’s quotation from completed initial measurements and preset prices."><Notice error={resource.error}/>{resource.loading?<p>Loading quotation…</p>:resource.data?<QuoteEditor key={resource.data.flow?.revision??0} data={resource.data} projectId={projectId} reload={resource.reload}/>:null}</Workspace>;
}
