"use client";
import Link from 'next/link';
import { useState } from 'react';
import type { FieldProject } from '@/lib/offline/types';
import { needsSalesFollowUp,projectStage,projectStages,stageDetails,projectLink } from '@/lib/workflow/stages';
import { button,card,field,Notice,useResource,useNow,Workspace } from './ui';
export function SalesDashboard(){
 const {data,error,loading}=useResource<{projects:FieldProject[]}>('/api/workspace');const [stage,setStage]=useState('all');const [search,setSearch]=useState('');const [due,setDue]=useState('all');
 const projects=data?.projects??[];const now=useNow();
 const waiting=projects.filter(needsSalesFollowUp);const overdue=waiting.filter(p=>p.next_follow_up_at&&Date.parse(p.next_follow_up_at)<now);
 const selected=projects.filter(p=>(stage==='all'||projectStage(p)===stage)&&(`${p.project_name} ${p.project_number} ${p.phone??''}`.toLowerCase().includes(search.toLowerCase()))&&(due==='all'||(needsSalesFollowUp(p)&&(due==='unscheduled'?!p.next_follow_up_at:!!p.next_follow_up_at&&Date.parse(p.next_follow_up_at)<now))));
 return <Workspace title="Dashboard" description="Track every project from registration to a signed contract and Operations."><Notice error={error}/><div className="mb-7 flex flex-wrap gap-3"><Link href="/intake" className={button}>New client & project</Link><Link href="/mini-crm" className="min-h-12 rounded-md border border-slate-300 bg-white px-5 py-3 text-sm font-semibold text-slate-700">Open CRM follow-ups</Link></div>{loading?<p>Loading project stages…</p>:<>
 <section aria-label="Project overview" className="mb-7 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Total projects',projects.length],['Awaiting sales action',waiting.length],['Overdue follow-ups',overdue.length],['Signed / Operations',projects.filter(p=>['handoff','operations'].includes(projectStage(p))).length]].map(([label,count])=><div key={label} className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-xs font-medium text-slate-500">{label}</p><p className={`mt-2 text-3xl font-semibold ${label==='Overdue follow-ups'&&Number(count)>0?'text-amber-700':'text-slate-900'}`}>{count}</p></div>)}</section>
 <section aria-label="Filter by project stage"><div className="mb-3 flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">Project stages</h2><button type="button" onClick={()=>{setStage('all');setDue('all');setSearch('');}} className="min-h-11 px-2 text-sm font-semibold text-blue-600">Show all projects</button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{projectStages.filter(s=>s.id!=='closed'||projects.some(p=>projectStage(p)==='closed')).map(s=>{const count=projects.filter(p=>projectStage(p)===s.id).length;return <button key={s.id} type="button" aria-pressed={stage===s.id} onClick={()=>{setStage(stage===s.id?'all':s.id);setDue('all');}} className={`flex min-h-24 items-center justify-between gap-4 rounded-lg border p-4 text-start transition focus-visible:outline-2 focus-visible:outline-blue-600 ${stage===s.id?'border-blue-600 bg-blue-50 text-blue-900':'border-slate-200 bg-white text-slate-700 hover:border-blue-300'}`}><span><span className="block text-sm font-semibold">{s.label}</span><span className="mt-1 block text-xs text-slate-500">{s.action}</span></span><span className="text-2xl font-semibold tabular-nums">{count}</span></button>;})}</div></section>
 <section className="mt-8"><div className="mb-5 grid gap-4 sm:grid-cols-2"><label className="text-sm">Find a project<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Client name, project number or phone" className={field}/></label><label className="text-sm">Follow-up priority<select aria-label="Follow-up priority" value={due} onChange={e=>setDue(e.target.value)} className={field}><option value="all">All projects in this stage</option><option value="overdue">Overdue follow-ups</option><option value="unscheduled">Needs a follow-up date</option></select></label></div><h2 className="mb-4 text-lg font-semibold">{stage==='all'?'All projects':projectStages.find(s=>s.id===stage)?.label} <span className="text-sm font-normal text-slate-500">· {selected.length}</span></h2>{!selected.length?<p className={card}>No projects match this view.</p>:<div className="space-y-3">{selected.map(p=><article key={p.id} className={card}><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-semibold text-blue-600">{p.project_number}{p.pending?' · Saved on device':''}</p><h3 className="mt-1 text-lg font-semibold">{p.project_name}</h3></div><span className="h-fit rounded-md bg-slate-100 px-3 py-2 text-xs font-medium">{stageDetails(p).label}</span></div><p className="mt-3 text-xs text-slate-500">Created by {p.registeredBy} · Outdoor Sales: {p.assignedOutdoorSales??'Not assigned'}</p>{needsSalesFollowUp(p)&&<p className={`mt-3 text-sm ${p.next_follow_up_at&&Date.parse(p.next_follow_up_at)<now?'text-amber-800':'text-slate-600'}`}>{p.next_follow_up_at?`Follow-up: ${new Date(p.next_follow_up_at).toLocaleString()}`:'Follow-up date not set'}</p>}<div className="mt-4 flex flex-wrap gap-5 text-sm font-semibold text-blue-600"><Link href={projectLink(p)} className="min-h-11 py-2">Open project →</Link><Link href={`/projects/${p.id}/follow-ups`} className="min-h-11 py-2">Follow-up history</Link></div></article>)}</div>}</section>
 </>}</Workspace>;
}
